# Generated by Django 4.0.1 on 2022-03-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1984-03-01'),
            preserve_default=False,
        ),
    ]
